### ISSUE TITLE
replace: true doesn't play nicely with multiple bindings via v-with

### ISSUE THREAD

**Issue by dhruvio** [yyx990803/vue#870] opened 2015-05-27 06:03 UTC
Let's say a parent component's template has a HTML element: `<div v-component='child' v-with='one: 1, two: 2, three: 3'></div>`.

Further, the child component inside the parent component, has the `replace` option set to `true`.

The consequent result is that the child component only receives the binding for `one` whereas `two` and `three` are undefined.

Let me know if you need any further clarifications.

Thanks,
Dhruv

**Comment by yyx990803** [comment] 2015-05-27 14:14
What version are you using? I can't reproduce this on 0.11.10, please include a repro in the format of a jsfiddle.

**Comment by dhruvio** [comment] 2015-05-27 17:48
http://jsfiddle.net/36eyxv35/1/

I have commented out the `replace: true` in the parent VM. If you uncomment it, it will throw an error in the console.

**Comment by yyx990803** [comment] 2015-05-27 18:51
Thanks for the fiddle. The issue has been fixed in the current 0.12.0-beta, you can upgrade to that or you might want to add a top-level element to your component (e.g. `<span>{{json}}</span>`).

**Closed** 2015-05-27 19:06 UTC

**Comment by dhruvio** [comment] 2015-05-27 22:50
Thank you
