### ISSUE TITLE
Add a preventDefault event filter

### ISSUE THREAD

**Issue by skyrpex** [yyx990803/vue#1369] opened 2015-09-28 12:39 UTC
I find it pretty cumbersome to add an event parameter and write ```e.preventDefault();``` in every single method of my components.

It would be nice to add a ```v-on``` filter that automatically does that. It would be used like this:

```js
<form v-on="click:submit | preventDefault"> ... </form>
```

It looks better to me because the method itself shouldn't really know about the original event that triggered the call (but the template should, and does).

**Comment by SeoFood** [comment] 2015-09-28 15:44
Yep same for me at the moment i do use a custom directive like:

`<a href="#" v-popup="{ref: 'more', position: 'bottom center'}" v-prevent-default>`

**Comment by posva** [comment] 2015-09-28 18:05
@SeoFood What about sharing that directive? :stuck_out_tongue:

**Comment by SeoFood** [comment] 2015-09-28 18:09
Sure:

```javascript
module.exports = {
        bind: function () {
            this.el.addEventListener ('click', function(e) {
                e.preventDefault();
            });
        },

        update: function (value) {
        }
};
```

**Comment by cmmu** [comment] 2015-09-29 09:41
This would be very useful in my project. SeoFood, I have tried adding the unbind clause to the code for cleanup, but in this case it stops working when I use it in combination with v-if directive. Not sure if it's even necessary to unbind it.

```javascript
var handler = function(e) { e.preventDefault() }
Vue.directive("prevent-default", {
	bind: function() {
		this.el.addEventListener("click", handler)
	},
	unbind: function() {
		this.el.removeEventListener("click", handler)
	}
})
```

**Comment by cmmu** [comment] 2015-09-29 09:41
This would be very useful in my project. SeoFood, I have tried adding the unbind clause to the code for cleanup, but in this case it stops working when I use it in combination with v-if directive. Not sure if it's even necessary to unbind it.

```javascript
var handler = function(e) { e.preventDefault() }
Vue.directive("prevent-default", {
	bind: function() {
		this.el.addEventListener("click", handler)
	},
	unbind: function() {
		this.el.removeEventListener("click", handler)
	}
})
```

**Comment by uwe** [comment] 2015-09-29 13:25
+1

**Comment by alioygur** [comment] 2015-09-29 15:43
+1

**Comment by skyrpex** [comment] 2015-09-30 10:43
I've created a more complete version. It automatically handles button, anchor and form elements.

You can find the [gist here](https://gist.github.com/skyrpex/9c769394e3554f6abac0).

**Comment by karevn** [comment] 2015-10-01 16:24
+1

**Comment by yyx990803** [comment] 2015-10-01 19:16
Would it make sense to always call `preventDefault` on certain events? e.g. `click` on `<a> <button>`and `submit` on `<form>` in particular. Is there any legit use cases where you **don't** want to preventDefault for these three cases?

**Comment by skyrpex** [comment] 2015-10-01 19:45
I guess it makes sense only if the element has the v-on directive on it!

**Comment by yyx990803** [comment] 2015-10-01 19:46
@skyrpex of course, we are talking in the context of `v-on` behavior.

**Comment by simplesmiler** [comment] 2015-10-01 20:30
A thing to consider is `<a>` behavior for click with modifier keys (ctrl, shift) and/or other-than-left mouse button. There is nothing more infuriating than an app ignoring middle click to open link in a new tab.

**Comment by mark-hahn** [comment] 2015-10-01 22:36
> e.g. click on <a> <button>

I can easily imagine wanting multiple things to happen on a click.  Like
closing all ancestor components.

**Comment by thelinuxlich** [comment] 2015-10-02 01:23
Maybe a special option, like KO:

http://knockoutjs.com/documentation/click-binding.html#note-4-preventing-the-event-from-bubbling

**Comment by karevn** [comment] 2015-10-02 05:57
I think "make it explicit" approach should be applied to match developer expectations. But... May be, yet another attribute name modifier, like:

```vue
<button @click.pd="handler">Click me</button>
or
<button @click:="handler">Click me</button>
```

**Comment by thelinuxlich** [comment] 2015-10-02 06:05
hmm nice suggestion, +1 for attribute modifier

I think it should call ```preventDefault``` automatically and if you want the opposite:

 ```
<button @click.bubble="handler">Click me</button>
````

**Comment by karevn** [comment] 2015-10-02 06:30
@thelinuxlich looks good, but the problem is that events like "click" will not bubble by default, while events like mouseover should bubble in most cases... So defaults will be different for different event types, which does not look good for me...

**Comment by mark-hahn** [comment] 2015-10-02 06:33
> defaults will be different for different event types,

That would be horrible.

**Comment by thelinuxlich** [comment] 2015-10-02 06:34
Agreed, then keep the original behavior and when you want to ```preventDefault```:

```
<button @click.unbubble="handler">Click me</button>
```

**Comment by karevn** [comment] 2015-10-02 06:35
```vue
<button @click.stop="handler">Click me</button>
<button @click.prevent="handler">Click me</button>
```
?

**Comment by thelinuxlich** [comment] 2015-10-02 06:44
good options too!

**Comment by posva** [comment] 2015-10-02 07:07
the options proposed by @karevn look better in my opinion because they remind of the functions `stopPropgation()` and `preventDefault()`

This is the first time I ever heard about `bubble` and `unbubble` :laughing: 
Funny name BTW

**Comment by Rastishka** [comment] 2015-10-02 14:34
Event bubbling, event capturing and event propagation - are 3 different things, are they?
```
<button @click.stopBubbling="handler">Click me</button>
<button @click.stopPropagation="handler">Click me</button>
<button @click.stopAll="handler">Click me</button>
```

**Comment by young-steveo** [comment] 2015-10-02 14:51
I like the idea of always preventing default, unless specified.  Most of the time, when adding a click handler to an element, the default behavior is not desired.  What about:

```html
<!-- will propagate, will prevent default -->
<button @click="handler">Click me</button>

<!-- will propagate, will not prevent default -->
<button @click.default="handler">Click me</button>

<!-- will stop propagation, will prevent default -->
<button @click.stop="handler">Click me</button>
```

**Comment by JosephSilber** [comment] 2015-10-02 14:53
Does anyone know what Angular does? They definitely prevent some events (submit comes to mind).

**Comment by yyx990803** [comment] 2015-10-02 15:06
@JosephSilber looks like submit is the only one. From ng's docs:

> Additionally it prevents the default action (which for form means sending the request to the server and reloading the current page), but only if the form does not contain action, data-action, or x-action attributes.

**Comment by yyx990803** [comment] 2015-10-02 15:58
@young-steveo it just seems harder to remember. Think of it like this:

- Without any modifier, the behavior is the same as native browser behavior
- `.prevent` means `preventDefault()` will be called for you.
- `.stop` means `stopPropagation()` will be called for you.

Seems to be much simpler conceptually.

**Comment by yyx990803** [comment] 2015-10-02 19:23
Landed in 1.0 alpha/beta branches as `.stop` and `.prevent` modifiers. Can be used together.

**Closed by yyx990803** 2015-10-02 19:23 UTC
Labels: suggestion

**Comment by nervgh** [comment] 2015-10-21 14:14
This syntax not working with https://github.com/webpack/html-loader =(

Is there angular way for these cases? For example:
```html
<element v-on:click="toggle();$event.stopPropagation()"></element>
```

**Comment by yyx990803** [comment] 2015-10-21 14:33
@nervgh use https://github.com/vuejs/vue-html-loader

**Comment by nervgh** [comment] 2015-10-21 14:43
@yyx990803 thanks! :+1:
