### ISSUE TITLE
v-show can't be used in v-repeat 

### ISSUE THREAD

**Issue by ybbjegj** [yyx990803/vue#868] opened 2015-05-27 02:27 UTC
In the latest version of the vue.js, the use of v-repeat in the v-show, the v-show will appear abnormal information。
For example:

    <div v-repeat='require:requireList' class='require-item' data-pgId='{{require.pgId || require.pgid}}' v-show='require.remain'>
   </div>
Now tip the following error  “Error when evaluating expression "require.remain":
TypeError: Cannot read property 'remain' of undefined”。

**Comment by yyx990803** [comment] 2015-05-27 03:26
Closing as this not a bug - see vuejs/Discussion#164

**Closed by yyx990803** 2015-05-27 03:26 UTC
