### ISSUE TITLE
props with default values are not added to component data

### ISSUE THREAD

**Issue by thelinuxlich** [yyx990803/vue#1023] opened 2015-07-07 20:42 UTC
If I don't explicitly add them to the component element attribute

**Comment by yoelneiman** [comment] 2015-07-07 21:03
the whole idea of props is to pass data through attributes by setting a value

**Comment by thelinuxlich** [comment] 2015-07-07 21:20
then why the option of setting a default value on props configuration?

**Comment by karevn** [comment] 2015-07-07 22:24
@thelinuxlich take it the next way - props are "attributes", "data" is "default data or data fetched from external places", and all them are proxied to the Vue instance. So, it's "by design".

**Comment by thelinuxlich** [comment] 2015-07-07 22:26
ok, but no one explained yet what is the purpose of the default value on props.

**Comment by karevn** [comment] 2015-07-07 22:38
@thelinuxlich user the source, Luke :) The default value for props is literally a default value. For example, the next code:

    Vue.component 'cat', {
      props: {
        name: {default:  'Tom'}
      }
    }
and

So if you'll later use `<cat>` component - it's instance will have name = 'Tom'. And if you'll use `<cat name="Bob">`, it will have name="Bob". Please note, that these values are not mapped to `data` property - only to the Vue instance itself. There would be just no point in that. Also, Props always overwrite "data" keys.
Use the source, Luke! :)

**Comment by thelinuxlich** [comment] 2015-07-07 23:07
You described the desired behavior, if cat is missing the name attribute, it should default to "Tom", but that is not happening

**Comment by alchen** [comment] 2015-07-07 23:58
http://jsfiddle.net/alchen/rjqt2x91/11/

It's working as far as I can tell. Can you provide an example that doesn't work?

**Comment by yyx990803** [comment] 2015-07-08 02:30
Please make sure to provide a repro.

**Comment by paulpflug** [comment] 2015-07-12 14:24
I encountered the same problem.
I narrowed it down: props and data can't be used together and data wins
```coffee
var vm = new Vue(
  el: document.createElement('div'),
  props: 
    'c': 
      default: 1
  data: ->
    "b": 2
  )
console.log vm.c # undefined
console.log vm.b # 2
```
I think they should be usable together

**Comment by yyx990803** [comment] 2015-07-12 15:30
@paulpflug upgrade to latest version please? They do work together in 0.12.7.

**Comment by yyx990803** [comment] 2015-07-12 15:32
Fixed via 145fed71f92bebab6b14b6c5bbe584c6aecaca25

**Closed by yyx990803** 2015-07-12 15:32 UTC
Labels: need repro

**Comment by paulpflug** [comment] 2015-07-12 16:35
[no it doesn't ^^](https://jsfiddle.net/rjqt2x91/15/)

**Comment by azamat-sharapov** [comment] 2015-07-12 18:53
@paulpflug yyx990803/vue/dev/dist/vue.js [is not latest dev](https://github.com/yyx990803/vue/blob/dev/dist/README.md).

**Comment by ben-joostens** [comment] 2016-06-07 19:57
The following example is a bit verbose but unless data is set in the parent I cannot pass the prop, but if I set data, then the prop default is useless:

http://jsbin.com/xaperuleji/edit?html,js,output

What am I missing?

**Comment by kticka** [comment] 2016-09-17 23:25
Hi guys, does this works for object type prop?

`  
props:
    job:
      type: Object
      default: ->
        quantity:
          type: Number
          default: 1
`

My 'job' property is a raw object without quantity property, so I'm expecting it should be set by this configuration.

**Comment by igorkosta** [comment] 2017-12-19 09:12
Hi @ben-joostens,

have you figured out how to work around this issue. I have the same problem and cannot wrap my head around it :(
