### ISSUE TITLE
template with v-if attribute doesn't render on Safari [vuejs version v0.12.9]

### ISSUE THREAD

**Issue by qinbinhua601** [yyx990803/vue#1137] opened 2015-08-10 03:27 UTC
I ran into an issue while using vue on the mobile.I'm using template tag to create a three layer nested structure with v-if attribute.But the innermost layer wasn't able to render correctly on Safari,while it ran just well on chrome(android).
Here is the jsfiddle link.
http://jsfiddle.net/vq4utpd1/
You could try running it at safari & chrome to see the different renderings.

Does anybody ran into this issue before?
Any help will be appreciated!

Screenshot on Chrome:
![image](https://cloud.githubusercontent.com/assets/3437641/9158988/a2d34292-3f52-11e5-8cd4-5eed4754d5a0.png)
Screenshot on Safari:
![image](https://cloud.githubusercontent.com/assets/3437641/9158999/cedb906a-3f52-11e5-82ab-b880bb4bbbd2.png)

Thanks in advance, guys.

**Comment by yyx990803** [comment] 2015-08-10 03:31
Duplicate of https://github.com/yyx990803/vue/issues/1118 (already fixed)

**Closed by yyx990803** 2015-08-10 03:31 UTC

**Comment by qinbinhua601** [comment] 2015-08-10 03:42
@yyx990803 右大大，我很确定用了最新的12.9版本呀
jsfiddle link:
http://jsfiddle.net/qinbinhua601/vq4utpd1/1/
![image](https://cloud.githubusercontent.com/assets/3437641/9159110/e4837386-3f54-11e5-8e73-9124abe7310a.png)

**Comment by yyx990803** [comment] 2015-08-10 03:59
新版本刚发布，升级到 0.12.10 就有了
