### ISSUE TITLE
merging class attribute of svg component

### ISSUE THREAD

**Issue by fenivana** [yyx990803/vue#1100] opened 2015-07-30 04:17 UTC
```js
<!DOCTYPE html>
<html>
<body>
  <icon-check class="foo"></icon-check>
  <script src="node_modules/vue/dist/vue.js"></script>
  <script>
    Vue.component('icon-check', {
      template: '<svg class="icon-check" viewBox="0 0 14 11" xmlns="http://www.w3.org/2000/svg"><path fill="#15CC87" d="M1 6L0 7l4 4L14 1l-1-1-9 9-3-3z"/></svg>'
    });
    new Vue({
      el: 'html'
    });
  </script>
</body>
</html>
```

Result:
```html
<svg class="icon-check" viewBox="0 0 14 11" xmlns="http://www.w3.org/2000/svg"><path fill="#15CC87" d="M1 6L0 7l4 4L14 1l-1-1-9 9-3-3z"></path></svg>
```

BTW, "If both nodes have the same plain attribute, the template root node will take priority.", I think let instance override template default attributes will be more flexible.

**Comment by yyx990803** [comment] 2015-07-30 11:58
duplicate of https://github.com/yyx990803/vue/issues/1093

**Closed by yyx990803** 2015-07-30 11:58 UTC
