### ISSUE TITLE
_directives.length ERROR: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by kvdmolen** [yyx990803/vue#678] opened 2015-01-15 11:18 UTC
Using Vueify in an app (compiled in DEV) I get the following error:
```javascript
Uncaught TypeError: Cannot read property 'length' of null
```
From script.js:7557
```javascript
var originalDirCount = vm._directives.length
```
I use no custom directives. Error occurs only sometimes, very weird.

Any idea anyone?
Thanks!

More context on script.js:
```javascript
/**
	   * A linker function to be called on a already compiled
	   * piece of DOM, which instantiates all directive
	   * instances.
	   *
	   * @param {Vue} vm
	   * @param {Element|DocumentFragment} el
	   * @return {Function|undefined}
	   */
	
	  return function link (vm, el) {
	    var originalDirCount = vm._directives.length
	    if (paramsLinkFn) paramsLinkFn(vm, el)
	    if (nodeLinkFn) nodeLinkFn(vm, el)
	    if (childLinkFn) childLinkFn(vm, el.childNodes)
```

**Comment by mikend** [comment] 2015-01-20 10:39
I'm experiencing the same error. Had to revert back to 0.11.3 to make my app work again. This is almost definitely a bug. Could try doing some further investigations.

**Comment by yyx990803** [comment] 2015-01-20 16:43
This is actually pretty weird because it indicates the linker is called when the target vm is already destroyed. I would need a more isolated reproduction to identify the cause.

**Comment by agonbina** [comment] 2015-01-31 14:07
@kvdmolen can you repro this issue in a jsfiddle so we can all look into it?

**Comment by kvdmolen** [comment] 2015-02-04 12:38
@agonbina I will definitely try to pinpoint & isolate, but difficult because it happens only sometimes.
Though, it does happen right after an emit event:
```javascript
var store = module.exports = new Emitter()
store.emit('...')
```
After which (at the receiver) the v-component is updated:
```html
<div v-component="{{page}}"></div>
```
Perhaps that gives some first insight. It's according the [hackernews-example](https://github.com/yyx990803/vue-hackernews). I'll be working on isolating the issue!

**Comment by jcoffland** [comment] 2015-02-07 01:16
Please see my comment on issue #654 above.  I believe these issue are not the same but are related.

Events can cause components to be added or removed by changing variables which effect ```v-if``` or ```v-compoent="{{someVar}}"```.  This alters event propagation.  In the case of #654, the list of event listeners may change while the event code is traversing that same list.

I think the event propagation code should make a copy of the event listener list when it begins processing the list.  Then while iterating through the list it should check that each listener still exists before calling ```update()```.

**Comment by yyx990803** [comment] 2015-05-19 21:16
Closing since this has most likely been fixed by `v-if` and transclusion refactor.

**Closed by yyx990803** 2015-05-19 21:16 UTC
