### ISSUE TITLE
`v-with` fails silently if component has `replace: true` and more than 1 root element (fiddle included)

### ISSUE THREAD

**Issue by cheapsteak** [yyx990803/vue#701] opened 2015-02-02 17:57 UTC
The legacy 0.10 docs mentions having only 1 root element as a restriction to `replace`. 
Current version (0.11) seems to have `replace: true` work for components with multiple root elements, but v-with breaks with no warning.

[doesn't work - http://jsfiddle.net/r4h8p5jz/](http://jsfiddle.net/r4h8p5jz/)
[works - http://jsfiddle.net/r4h8p5jz/1/](http://jsfiddle.net/r4h8p5jz/1/)

```javascript
var ComponentA = Vue.extend({
    //template: '<div>{{bar}}</div>', // this works
    template: '<div>{{bar}}</div><div></div>', // this doesn't
    replace: true
});

new Vue({
    el: 'body',
    template: '<component-a v-with="bar: foo"></component-a>',
    data: {
        foo: 'Test Test Test Test'
    },
    components: {
        'component-a': ComponentA
    }
});
```

**Comment by yyx990803** [comment] 2015-02-02 19:51
Thanks, seems to be duplicate of #655

**Closed by yyx990803** 2015-02-02 19:51 UTC
