### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by yotamN2** [yyx990803/vue#656] opened 2014-12-26 13:44 UTC
Do you plan to add Typescript definition file?

**Comment by yyx990803** [comment] 2015-01-02 02:46
I'll close this as a duplicate of #478 - feel free to continue the discussion there (I've briefly looked at a t.ds file for Vue but didn't have the time to actually write it - maybe @indus' solution can help)

**Closed by yyx990803** 2015-01-02 02:46 UTC
