### ISSUE TITLE
radio buttons with v-model in v-repeat explode after splice

### ISSUE THREAD

**Issue by katywings** [yyx990803/vue#1161] opened 2015-08-14 11:39 UTC
Hello my friends

I just found a little problem which was not solvable after about 1 hour of searching:

Having something like this (just example code!):

    <div v-repeat="items">
        <input value="cool" radio v-model="picked" name="arr[][{{'item' + $index]}}">
        <input value="fantastico" radio v-model="picked" name="arr[][{{'item' + $index]}}">
        <input value="uncool" radio v-model="picked" name="arr[][{{'item' + $index]}}">
        <button>Add item</button>
    </div>

Button Code (just example code!):

    this.items.splice( e.targetVM.$index + 1, 0, {
        picked: 'cool'
    });

Problem:
When you add an item *c* in between two items **a** and **b** with splice, the item **b** s checked state gets exploded.
Items after item b do work xD. But Item **b** s checked state is lost in space. Thats not so amazing, and when you iterate through data - of course after the addition, the data is correct, which in this case is strange too xD...

The `track_by`Directive didnt help, i tried it with uids.

Do you have an idea?

Thanks in advance and have a nice weekend! :smiley:

**Comment by yyx990803** [comment] 2015-08-14 14:11
Please provide a debuggable reproduction.

**Comment by katywings** [comment] 2015-08-14 15:18
I added examples because it is a locked professional project, I can't give you access :/

---- Evan You schrieb ----

**Comment by simplesmiler** [comment] 2015-08-14 15:57
@katywings Evan was asking for a [sscce](http://sscce.org/) fiddle. You can start from [here](http://jsfiddle.net/simplesmiler/9zegjc4g/) (vue@0.12.10).

**Comment by katywings** [comment] 2015-08-14 19:26
Ahh i've really miss-understood that xD.

Yeah I can create one, but not today! 😏

---- Denis Karabaza schrieb ----

**Comment by katywings** [comment] 2015-08-15 08:08
Okay here it is:
http://jsfiddle.net/5m0nw7bh/3/

Its starting with two items a and b

Just press the add item button on the first item. It will create a item c in between a and b. But the item b radiuses looses its checked state. 


Thanks a lot for your help!

**Comment by simplesmiler** [comment] 2015-08-15 19:01
I'm not sure why, but `track-by="$index"` helps.

**Comment by yyx990803** [comment] 2015-08-15 19:56
Found the cause: when you insert the new instance... its radio inputs have the same `name` attribute with the instance after it (which is not updated yet because the `name` is based on `$index`). So at that moment the page has 6 inputs with the same `name`, thus selecting one of them deselects the others...

What I suggest here is simply remove the name attribute, because you don't need it. When you submit the form, just send in the `items` array instead of getting it from the form...

**Comment by katywings** [comment] 2015-08-16 07:21
@yyx990803: Yeah, its the priority of the model which updates before the change of the names...

Is it impossible to fix this in the framework? :)
Something like:
-> pause v-model Computations
-> update v-repeat variables ($index)
-> resume v-model Computations

I think this framework will get widely adapted in the future and so this problem will occur more and more, and like in my case it is not that easy to switch from a form action submit with input name elements to a $.ajax submit.

@simplesmiler: That looks too easy! No :dancer:  thank you man I will try your workaround! Very strange that track-by $index helps, two days ago, I tried track-by uid which didnt help ^^

**Comment by katywings** [comment] 2015-08-19 08:14
@simplesmiler: Your workaround works perfectly, thank you!

**Comment by yyx990803** [comment] 2015-08-19 18:10
Closing this because you have found a workaround, and this is an edge case (or rather a non-recommended pattern) that doesn't seem to justify the amount of effort to work around it.

**Closed by yyx990803** 2015-08-19 18:10 UTC

**Comment by simplesmiler** [comment] 2015-08-19 20:04
@yyx990803 I think it worth to mention this in docs, the fact that radio buttons with `v-model` do not require `name` attribute to be radio.
Also radio buttons example in http://vuejs.org/guide/forms.html should probably be stripped of `name` attributes.

**Comment by yyx990803** [comment] 2015-08-19 20:19
@simplesmiler yeah, good idea.
