### ISSUE TITLE
Dropdown list value should support representing arbitrary JavaScript objects, not just strings

### ISSUE THREAD

**Issue by J-F-Liu** [yyx990803/vue#1183] opened 2015-08-20 08:04 UTC
For example, the following code currently doesn't work.
``````````
  <select v-model="chosenTicket" options="ticketOptions">
    <option value="">Choose...</option> 
  </select>
  <button v-attr="disabled: !chosenTicket" v-on="click: resetTicket">Clear</button>
  <p v-if="chosenTicket">You have choosen <b>{{chosenTicket.name}}</b>(${{chosenTicket.price}})</p>
``````````
``````````
new Vue({
  el: "#app",
  data: {
    tickets: [
      { name: "Economy", price: 199.95 },
      { name: "Business", price: 449.22 },
      { name: "First Class", price: 1199.99 }
    ],
    chosenTicket: null
  },
  computed: {
    ticketOptions: function() { 
      return this.tickets.map(function(ticket){
        return {text: ticket.name, value: ticket};
      });
    }
  },
  methods: {
    resetTicket: function() { 
      this.chosenTicket = null;
    }
  }
});
``````````
knockout.js supports this and it is extremely useful for data binding of cascading dropdowns.
Like http://knockoutjs.com/examples/cartEditor.html

**Comment by yyx990803** [comment] 2015-08-20 14:06
Duplicate of #1115 - Yes, this is going to be added.

**Closed by yyx990803** 2015-08-20 14:06 UTC
