### ISSUE TITLE
Is the scope for repeated component right?

### ISSUE THREAD

**Issue by TerenceZ** [yyx990803/vue#1081] opened 2015-07-27 10:09 UTC
For the example followed, the `content` is always `content: ` without the `$index` value, and the property `prop` is always empty. The first case is because the `$index` is resolved using the `comp`'s parent scope, and the last case is because the properties are initialized before the meta data.

```html
<comp v-repeat="array" prop="{{$index}}">content: {{$index}}</comp>
```

**Comment by yyx990803** [comment] 2015-07-27 14:05
Both are expected behavior: the first case is exactly what you described; the second case is because the content is transcluded, so it is also resolved in parent scope.

**Closed** 2015-07-27 14:06 UTC

**Comment by TerenceZ** [comment] 2015-07-28 02:12
So it means if I want to use the repeat meta info, I have to wrap a `template` around the `component`? But if the `component` should communicate with specified type parent, the repeated template will break this...

**Comment by yyx990803** [comment] 2015-07-28 15:21
If the component is used with `v-repeat`, `$index` and other meta info will be available inside the component automatically. You don't have to explicitly pass it in.

As for the parent - you can check if the parent is an inline repeat wrapper by checking `$parent.$options._repeat`. This is kinda dirty but should be enough for the use case. Definitely can be improved later.
