### ISSUE TITLE
Ongoing transitions break when browser tab on background

### ISSUE THREAD

**Issue by azamat-sharapov** [yyx990803/vue#818] opened 2015-05-05 19:47 UTC
1. Open [this simple slider on Vue](http://jsfiddle.net/azamatsharapov/dkbfebee/1/).
2. Wait for slider to start and open browser console on that page.
3. Switch to another browser tab, wait a minute or so and come back to fiddle and look at console, you should see error. (you can open console as a separate window, so that you can look at it and wait until error popus up).

Error: `Uncaught TypeError: Cannot read property '__v_trans' of null`

**Comment by yyx990803** [comment] 2015-05-05 21:50
This is caused by transitionend events not firing until the page regains focus, and only happens for `out-in` mode. Fixed in `dev` branch now.

**Closed by yyx990803** 2015-05-05 21:50 UTC
